# CloudFormationNetworkVPC.yml
# ============================

AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for the Wordpress VPC 

Resources:

  WordpressVpc:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: WordPressNetwork

  InternetGateway:
    Type: AWS::EC2::InternetGateway
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref WordpressVpc

  SubnetAZa:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Join ["", [!Ref "AWS::Region", "a"]]
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: true
      VpcId: !Ref WordpressVpc
      Tags:
        - Key: Name
          Value: SubnetAZa
  SubnetAZaRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref SubnetAZa
  SubnetAZb:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Join ["", [!Ref "AWS::Region", "b"]]
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: false
      VpcId: !Ref WordpressVpc
      Tags:
        - Key: Name
          Value: SubnetAZb

  SubnetAZbRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref SubnetAZb

  NACLPublic:
    Type: AWS::EC2::NetworkAcl
    Properties:
      Tags:
        - Key: Name
          Value: NACLPublic
      VpcId: !Ref WordpressVpc

  NACLPublicIngressAll:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: False
      RuleNumber: 100
      RuleAction: allow
      NetworkAclId: !Ref NACLPublic
      PortRange: 
        From: 0
        To: 65535
      Protocol: -1
  NACLPublicEgressAll:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: True
      RuleNumber: 100
      RuleAction: allow
      NetworkAclId: !Ref NACLPublic
      PortRange: 
        From: 0
        To: 65535
      Protocol: -1

  SubnetNACLAssociationSubnetAZa:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref NACLPublic
      SubnetId: !Ref SubnetAZa

  SubnetNACLAssociationSubnetAZb:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref NACLPublic
      SubnetId: !Ref SubnetAZb

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: PublicRouteTable
      VpcId: !Ref WordpressVpc
  PublicRoutePublicInternet:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

Outputs:
  WordpressVpcId:
    Value: !Ref WordpressVpc

  SubnetAZa:
    Value: !Ref SubnetAZa
  SubnetAZb:
    Value: !Ref SubnetAZb

    